packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  defu: ^6.1.4
  local-pkg: ^1.1.1
catalogs:
  cli:
    '@antfu/eslint-config': ^4.19.0
    '@antfu/ni': ^24.4.0
    bumpp: ^10.2.2
    lint-staged: ^15.5.2
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.3
    typescript: ^5.9.2
    unbuild: ^3.6.0
    vite: ^6.3.5
  inlined:
    '@antfu/utils': ^9.2.0
  lint:
    eslint: ^9.32.0
    typescript-eslint: ^8.39.0
    eslint-config-flat-gitignore: ^2.1.0
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^22.17.0
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
