packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  defu: ^6.1.4
  local-pkg: ^1.1.1
catalogs:
  cli:
    '@antfu/eslint-config': ^4.19.0
    '@antfu/ni': ^24.4.0
    bumpp: ^10.2.2
    lint-staged: ^15.5.2
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.3
    typescript: ^5.9.2
    unbuild: ^3.6.0
    vite: ^6.3.5
    eslint-typegen: ^2.3.0
  inlined:
    '@antfu/utils': ^9.2.0
  lint:
    '@eslint-react/eslint-plugin': ^1.52.3
    eslint: ^9.32.0
    typescript-eslint: ^8.39.0
    eslint-config-flat-gitignore: ^2.1.0
    '@eslint/js': ^9.32.0
    '@stylistic/eslint-plugin': ^5.2.2
    '@typescript-eslint/types': ^8.39.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-hyoban: ^0.6.1
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-package-json: ^0.51.0
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react-google-translate: ^0.1.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-regexp: ^2.9.1
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-tailwindcss: npm:@hyoban/eslint-plugin-tailwindcss@4.0.0-alpha.12
    eslint-plugin-unicorn: ^60.0.0
    eslint-plugin-unused-imports: ^4.1.4
    globals: ^16.3.0
    jsonc-eslint-parser: ^2.4.0
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^22.17.0
    '@types/eslint-plugin-tailwindcss': ^3.17.0
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
